slurm_interface: cli # can be either cli or http
users_mapping:
  - user: Benoit Leveugle
    mail: benoit.leveugle@atos.net
    local_user: kirby
    ssh_private_key_b64: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEWXhSNVpqZHZSbVBRWDhYTithdXFjaUFOcyszUDdRQ3BVcDdrK0Yvd1Evd0FBQUppMHE4aGJ0S3ZJCld3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRFl4UjVaamR2Um1QUVg4WE4rYXVxY2lBTnMrM1A3UUNwVXA3aytGL3dRL3cKQUFBRURFODJoNVNtSDY4a0k2OXA0VEJQek1CUGJwN2hnejlLNHFNaVMvSis2bVBOakZIbG1OMjlHWTlCZnhjMzVxNnB5SQpBMno3Yy90QUtsU251VDRYL0JEL0FBQUFEbTk0WldScGIyNXpRSEJ5YVcxaEFRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"
